# Generated by Django 4.1.7 on 2023-03-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_verified_email_emailverification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverification',
            old_name='experation',
            new_name='expiration',
        ),
    ]
